import { SiteHeader, SiteFooter } from '@/components/brandon/header';

export default function TermsPage() {
  return (
    <div className="flex min-h-screen flex-col bg-background text-foreground">
      <SiteHeader />

      <main className="flex flex-1 flex-col items-center px-6 pt-16 pb-24">
        <div className="mx-auto flex w-full max-w-3xl flex-col gap-6 text-foreground/90">
          <h1 className="font-serif text-4xl font-medium tracking-tight sm:text-5xl">
            Terms of Service
          </h1>
          <p className="text-xs font-mono text-muted-foreground">Updated September 2026</p>

          <div className="flex flex-col gap-6 text-sm leading-relaxed border-t border-border pt-6">
            <h2 className="font-serif text-2xl font-medium text-foreground">1. Nature of the Service</h2>
            <p>
              What Brandon Thinks turns messaging logs uploaded by users into comedic, psychological, and conversational analysis reports generated by artificial intelligence.
            </p>

            <h2 className="font-serif text-2xl font-medium text-foreground">2. Entertainment Disclaimer</h2>
            <p>
              All reports are provided for entertainment purposes. Artificial intelligence may misinterpret context or generate subjective characterizations. Reports do not constitute psychological, legal, medical, or relationship counseling and should never be used as the sole basis for major life decisions.
            </p>

            <h2 className="font-serif text-2xl font-medium text-foreground">3. User Responsibility</h2>
            <p>
              You must have the legal right to upload the conversation logs you submit. You must not use this service to harass, defame, or harm any individual.
            </p>
          </div>
        </div>
      </main>

      <SiteFooter />
    </div>
  );
}
